apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 300%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      service: "redis"
  template:
    metadata:
      labels:
        service: "redis"
    spec:
      {{ if .Values.initContainers.enabled }}
      initContainers:
      {{ if .Values.initContainers.somaxconn }}
        - image: "alpine"
          name: "increase-somaxconn"
          securityContext:
            privileged: true
          command:
            - "/bin/sh"
            - "-c"
            - "sysctl -w net.core.somaxconn=4096"
      {{ end }}
      {{ if .Values.initContainers.disableTHP }}
        - name: "disable-thp"
          image: "alpine"
          volumeMounts:
            - name: "host-sys"
              mountPath: "/host-sys"
          securityContext:
            privileged: true
          command:
            - "sh"
            - "-c"
            - "echo madvise >/host-sys/kernel/mm/transparent_hugepage/enabled && echo madvise >/host-sys/kernel/mm/transparent_hugepage/defrag"
      {{ end }}
      {{ end }}
      containers:
        - name: "redis"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "4-alpine" }}"
          {{ if .Values.args }}
          args:
{{ toYaml .Values.args | indent 12 }}
          {{ end }}
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
        {{ if .Values.metrics.enabled }}
        - name: "redis-exporter"
          image: "{{ .Values.redisExporter.image.repository }}:{{ .Values.redisExporter.image.tag | default "v0.14" }}"
          ports:
            - name: metrics
              containerPort: 9121
          resources:
{{ toYaml .Values.metrics.resources | indent 12 }}
        {{ end }}
      volumes:
        {{ if .Values.initContainers.disableTHP }}
        - name: "host-sys"
          hostPath:
            path: "/sys"
        {{ end }}
        - name: data
          emptyDir: {}
