{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: redis
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      service: redis
  podMetricsEndpoints:
    - port: metrics
{{- end }}
